import type { Emitter } from "./types";
import type { Relation } from "../core/model";
import { buildNameResolver } from "./names";
import { resolveRelationLabel } from "./label";

// erd (BurntSushi)'s grammar requires unquoted entity/attribute names to
// match [A-Za-z_][A-Za-z0-9_]* — a whitelist, not a blacklist of specific
// unsafe characters the way hasSpace/hasHyphen (quote.ts) work for other
// emitters — so this format gets its own regex-based check instead of
// composing from those primitives. Backtick is used since it's never itself
// produced by any --case mode and is one of three equivalent quote
// characters the grammar accepts (see docs/erd-format-reference.md §2.1).
function quoteIdent(id: string): string {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(id) ? id : `\`${id}\``;
}

function escapeLabel(label: string): string {
  return label.replaceAll('"', "'");
}

// Cardinality tokens per docs/erd-format-reference.md §7.2: the child (`to`)
// end is always optional ("?" for 1-1, "*" for 1-n/n-n — nothing in a FK
// model forces a parent row to have a matching child row); the parent
// (`from`) end is "1" unless isFromOptional says the FK on `to` is
// nullable, in which case it drops to "?". n-n never sets isFromOptional,
// so both ends are "*".
function toToken(rel: Relation): string {
  return rel.type === "1-1" ? "?" : "*";
}

function fromToken(rel: Relation): string {
  if (rel.type === "n-n") return "*";
  return rel.isFromOptional ? "?" : "1";
}

export const erEmitter: Emitter = {
  format: "er",
  fileExtension: "er",
  emit(model, options) {
    const {
      typeMode,
      nameMode = "model",
      relationLabelMode = "both",
      caseMode = "preserve",
      inflectMode = "preserve",
    } = options;
    const names = buildNameResolver(model, nameMode, caseMode, inflectMode);

    const lines = ["# Generated by orm2erd.", "", "# Entities"];

    for (const entity of model.entities) {
      const entityAlias = names.entityAlias(entity.name);
      const entityLabelParts = [
        entityAlias && `alias: ${entityAlias}`,
        entity.description,
      ].filter((p): p is string => Boolean(p));
      const entityLabel =
        entityLabelParts.length > 0
          ? ` {label: "${escapeLabel(entityLabelParts.join(" | "))}"}`
          : "";
      lines.push(`[${quoteIdent(names.entityId(entity.name))}]${entityLabel}`);

      for (const field of entity.fields) {
        const prefix = `${field.isPrimaryKey ? "*" : ""}${field.isForeignKey ? "+" : ""}`;
        let displayType = typeMode === "native" ? field.nativeType : field.type;
        if (field.type === "enum") {
          displayType = "Enum";
        }
        const typeLabel = `${displayType}${field.isList ? "[]" : ""}`;
        const fieldAlias = names.fieldAlias(field);
        const labelParts = [
          `${typeLabel}, ${field.isNullable ? "null" : "not null"}`,
          field.isUnique && "unique",
          field.enumValues && `enum: ${field.enumValues.join(", ")}`,
          field.defaultValue && `default: ${field.defaultValue}`,
          fieldAlias && `alias: ${fieldAlias}`,
          field.description,
        ].filter((p): p is string => Boolean(p));
        lines.push(
          `  ${prefix}${quoteIdent(names.fieldId(field))} {label: "${escapeLabel(labelParts.join(" | "))}"}`,
        );
      }
      lines.push("");
    }

    lines.push("# Relationships");
    for (const rel of model.relations) {
      const label = resolveRelationLabel(model, rel, names, relationLabelMode);
      const labelSuffix = label ? ` {label: "${escapeLabel(label)}"}` : "";
      lines.push(
        `${quoteIdent(names.entityId(rel.to))} ${toToken(rel)}--${fromToken(rel)} ${quoteIdent(names.entityId(rel.from))}${labelSuffix}`,
      );
    }

    return lines.join("\n");
  },
};
