import type { Emitter } from "./types";
import { buildNameResolver } from "./names";

export const nomnomlEmitter: Emitter = {
  format: "nomnoml",
  fileExtension: "noml",
  emit(model, options) {
    const {
      typeMode,
      nameMode = "model",
      caseMode = "preserve",
      inflectMode = "preserve",
    } = options;
    // nomnoml has no entity alias syntax, so "both" mode falls back to the
    // physical identifier alone, same as "table" mode.
    const names = buildNameResolver(model, nameMode, caseMode, inflectMode);

    const lines = [
      "// Generated by orm2erd.",
      "",
      "#direction: right",
      "",
      "// Entities",
    ];

    for (const entity of model.entities) {
      lines.push(`[<table> ${names.entityId(entity.name)}|`);
      entity.fields.forEach((field, index) => {
        let displayType = typeMode === "native" ? field.nativeType : field.type;
        if (field.type === "enum") {
          displayType = `enum(${field.enumValues?.join(", ")})`;
        }
        const typeLabel = `${displayType}${field.isList ? "\\[\\]" : ""}`;
        const constraints = [
          field.isPrimaryKey && "PK",
          field.isForeignKey && "FK",
          field.isUnique && "unique",
          !field.isNullable && "NN",
        ].filter((c): c is string => Boolean(c));
        const fieldAlias = names.fieldAlias(field);
        const comments = [
          typeLabel,
          constraints.length > 0 && constraints.join(", "),
          field.defaultValue && "= " + field.defaultValue.replaceAll('"', "'"),
          fieldAlias && `alias: ${fieldAlias}`,
        ].filter((c): c is string => Boolean(c));
        const isLastField = index === entity.fields.length - 1;
        lines.push(
          `  ${names.fieldId(field)} | ${comments.join(" ")}${isLastField ? "" : " ||"}`,
        );
      });
      lines.push("]");
      lines.push("");
    }

    lines.push("// Relationships");
    for (const rel of model.relations) {
      // nomnoml's notation: 1 -- * = one-to-many, * -- * = many-to-many,
      // 1 -- 0..1 = one-to-one. The `to` end is always 0..1/* (optional)
      // — nothing in a FK model forces a parent row to have a matching
      // row on the FK-holding side — while the `from` end downgrades
      // from `1` to `0..1` when isFromOptional says the FK column is
      // nullable.
      const fromMarker = rel.isFromOptional ? "0..1" : "1";
      const symbol =
        rel.type === "1-n"
          ? `${fromMarker} -- *`
          : rel.type === "n-n"
            ? "* -- *"
            : `${fromMarker} -- 0..1`;
      lines.push(
        `[${names.entityId(rel.from)}] ${symbol} [${names.entityId(rel.to)}]`,
      );
    }

    return lines.join("\n");
  },
};
